
server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: InventoryManage
          uri: http://localhost:8080/inventoryManage
          predicates:
            - Path=/stude/**
        - id: OrderManagement
          uri: http://localhost:8081/OrderManagement
          predicates:
            - Path=/course/**
  config:
    import: "Optional:configserver: https://localhost:8088"


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka