spring:
  application:
    name: ShippingManagement
  config:
    import: "optional:configserver:https://localhost:8088"
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/Shipping?schema=public"
    username: "postgres"
    password: "Bree@2002!"
server:
  port: 8084
