spring:
  application:
    name: InventoryManage
  config:
    import: "optional:configserver:https://localhost:8088"
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/postgres?schema=public"
    username: "postgres"
    password: "Bree@2002!"

